language: go
go:
  - 1.6
services:
  - mysql
env:
    global:
      - USER=travis
      - DB=test_apps
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
before_script:
  - cat db_commands.sql | mysql -u travis
script:
  - go test -v -covermode=count -coverprofile=profile.cov github.com/sieveable/sieveable-profile/dbwriter
after_success:
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
